### ISSUE TITLE
Default rendering for non-supported types

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/uma_publist#11]
Currently, any item types which are not supported, will display a string "no bib type", e.g.

![no-bib-type](https://user-images.githubusercontent.com/5199995/27841248-0b1250a2-6100-11e7-96b7-317e7b8cbc90.jpg)

Instead we could just try to display a generic entry as good as possible, e.g. the template for journal article. That would be same procedure as for example the [csl citation styles](https://github.com/citation-style-language/styles/) are usually doing this.

A use case is for example, when we try to use the plugin for MADATA, e.g. try the query url `https://madata.bib.uni-mannheim.de/cgi/search/archive/simple?output=XML&_action_export_redir=Export&screen=Search&dataset=archive&order=&cache=&exp=0|1||archive|-|q::ALL:IN:alpers|-|`.

What do you think?

**Comment by sebeka** [comment]
Looks like, in madoc they are transformed to "Working Paper"
https://ub-madoc.bib.uni-mannheim.de/466/

Best would be to use the template for "research_paper" (publist4ubma2), because in madoc this is:
"Arbeitspapier". => working_paper

Here is a list most mappings:
XML - DEU - FORMATIERUNG
article - Zeitschriften-artikel - Zeitschriften-artikel
book - Buch - Buch
book_section - Buchkapitel - Buchkapitel
conference_item - Konferenz Beitrag - Konferenzbeitrag
dissertation - Dissertation - Dissertation
encyclopedia_article - encyclopedia article - Lexikonartikel
habilitation - Habilitation - Habilitation
journal - Journal - Zeitschrift/Schritenreihe
other - anderes - Sonstiges
preprint - preprint - Preprint
report - Bericht - Bericht
review - Review - Rezension
thesis - Thesis - Abschlussarbeit(Bachelor/Master)
research_paper -  Arbeitspapier - Arbeitspapier


We should change this in:
 publist4ubma2/Classes/Controller/PublicationController.php line 168
  "- $newPub->setBibType($publication['notype']);"
  "+ $newPub->setBibType($publication['research_paper']);"

Should I change this, or do you like?

Thank you,

Sebastian

**Comment by zuphilip** [comment]
No, the data from MADATA will be parsed correctly and `bibType` is set to `dataset`. That is not the problem here.

(Note, I am ignoring currently how to deal with non-supported types for querying, and rather work with the Query Url directly in the expert mode.)

However, the rendering is influenced by [Resources/Private/Partials/FrontendDefaultTemplate.html](https://github.com/UB-Mannheim/publist4ubma2/blob/master/Resources/Private/Partials/FrontendDefaultTemplate.html#L97) etc. files, where we have:
```html
{namespace m=Unima\Publist4ubma2\ViewHelpers}
<f:switch expression="{publication.bibType}">
	<f:case value="book">
		<m:renderNamesWithAnd somebody="{publication.editors}" />.
		{publication.publisher}, {publication.corpCreators} {publication.year}
		<strong> <f:link.external uri="{publication.usedLinkUrl}" target="_blank">{publication.title}</f:link.external> </strong>
		{publication.placeOfPub}<br />{publication.abstract}
	</f:case>
....
	<f:case default="TRUE">no bib type</f:case>
</f:switch>
```
Is there any reason for the last case to output just a constant string? If not, then I suggest to render also in this case the title, authors, etc. of the entry.

For example by just copying the lines for article to the last case, the result changes to:
![unknown-types](https://user-images.githubusercontent.com/5199995/27878704-697e3fb0-61bf-11e7-9694-4bb3aa640011.jpg)

The dates and titles will be corrected with my other commit.

What do you think? Are there any other (negative?) consequences of such a change?

**Comment by sebeka** [comment]
OK fine, you can do it in the fluid templates. (there should be 4 files for 4 templates)
What types you have in madoc in addition? Should we make them available in the query window in the backend?

PS: Can you send the above list with the eprint-ids of the 7 publications to Mrs. Schimpf?

**Comment by zuphilip** [comment]
Cool, I will work on the rendering and create a PR.

There are different types in MADATA compared to MADOC, e.g. `dataset`. However, in other EPrints I also have seen `teaching_resources` and others. We could possibly allow the users to define their special item types in some list and give them a label (or maybe EPrints has such a list itself?). This could be used for querying, but that is something I will look closer next.

With the latest commit the list above (from MADATA entries not MADOC) improved to:

![madata-publist](https://user-images.githubusercontent.com/5199995/27908042-3be0fbd4-624a-11e7-86e7-31514cc9678c.jpg)

(The metadata for these datasets or fine, and we start to support them also here, nothing we have to report back.)

**Comment by sebeka** [comment]
cool, Thank you!
I think, we should make a new version after the amount of changes.
Maybe we can do together, when we meet  for the conference stuff
