### ISSUE TITLE
Error in RDFa data

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/uma_publist#54]
A wrong `“` instead of `"` is used in the RDFa data of e.g. this page https://www.uni-mannheim.de/dws/research/focus-groups/web-based-systems-prof-bizer/

![rdfa-error](https://user-images.githubusercontent.com/5199995/58191693-6b29a580-7cbf-11e9-9555-dc0d9971f128.jpg)

However, I don't see where this comes from. @lsuma Do you have any ideas?

**Comment by sebeka** [comment]
Hi zuphilip,

I looked a little bit around abut found not something.
On our old wim server it is working:
https://ms.math.uni-mannheim.de/de/publications/

Sebastian

**Comment by lsuma** [comment]
The cause is not in the extension itself. There is post-processing of the complete code on the new website. The attribute typeOf was not properly recognized due to it being written in mixed case. I was able to fix this.

What we should do in the extension, though, is to uniformly use lower case "indexof" instead of camel case "indexOf". While HTML is case-insensitive (XML is a different story), it is generally considered better practice to only use lowercase. This also causes less trouble with JS libraries.

**Comment by lsuma** [comment]
Uniformly changed attribute indexof to lowercase.

**Comment by zuphilip** [comment]
I guess you mean `indexOf` and not `typeOf`. Thank you @lsuma for fixing this which looks now good. However, schema.org uses CamelCase and we still have it e.g. `schema:ScholarlyArticle`. Are you sure that one shouldn't think about a fix for the post-processing instead?

**Comment by lsuma** [comment]
Actually, I meant `typeof` in all of the instances. Please excuse the confusion.

As for changing the case - please mind I changed the attribute _names_ to lower case, **not** the _values_. The examples from schema.org all use lower case for the attributes (including typeof) as well, you can look it up here: https://schema.org/ScholarlyArticle , so we're actually closer to the standard now. I don't know of any standard which proposes camel case in HTML attribute names.

Nevertheless, I already fixed the post-processing problem as well independently of this, so mixed case won't be a problem in the future.

**Comment by zuphilip** [comment]
Ah, okay, I see. Thank you for the clarification. And thank you also for fixing the thing in the post-processing as well. I am comfortable now and this issue is resolved.
